language: java
jdk:
  - oraclejdk8
before_script:
  - chmod +x ./gradlew
  - chmod +x ./how-to-extend/adapter-starterkit/gradlew
script:
  - ./gradlew
  - cd ./how-to-extend/adapter-starterkit
  - ./gradlew clean test --info
