language: java
jdk:
  - oraclejdk8
before_install:
  - chmod +x ./gradlew
install:
  - ./gradlew publishToMavenLocal
before_script:
  - chmod +x ./how-to-extend/adapter-starterkit/gradlew
script:
  - ./gradlew clean test --info
  - cd ./how-to-extend/adapter-starterkit
  - ./gradlew clean test --info
